repos:
  - repo: 'https://github.com/prettier/prettier'
    rev: 1.15.3
    hooks:
    -   id: prettier
        files: '/.*\.(js|html)$'
  - repo: 'https://github.com/awebdeveloper/pre-commit-stylelint'
    rev: 'c4c991cd38b0218735858716b09924f8b20e3812'
    hooks:
    -   id: stylelint
        additional_dependencies:
        - 'stylelint@9.10.1'
        - 'stylelint-scss@3.10.1'
        - 'stylelint-config-recommended-scss@3.3.0'
        files: '/.*\.(scss)$'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'b9ab52bbd195c8f951905fba4988e901d392b2d0'
    hooks:
    -   id: eslint
        additional_dependencies:
        - 'eslint@5.16.0'
        - 'eslint-config-airbnb@17.1.0'
        - 'eslint-config-prettier@5.0.0'
        - 'eslint-plugin-import@2.17.3'
        - 'eslint-plugin-jsx-a11y@6.2.1'
        - 'eslint-plugin-react@7.13.0'
        # files: '/.*\.(js)$'
        files: 'docs/config'
